// Live browser regression: no private research content is sent to the LLM.
import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[], dataRequests=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(/\/api\/(oceanography|biodiversity\/obis|fisheries\/effort)/.test(r.url()))dataRequests.push(r.url());});
  await page.goto('http://127.0.0.1:3000');
  await page.getByRole('button',{name:'Explore',exact:true}).click();
  const load=page.getByRole('button',{name:'Load data',exact:true});
  await expect(load).toBeEnabled();
  expect(dataRequests).toHaveLength(0);
  await page.getByRole('button',{name:'Arabian Sea',exact:true}).click();
  await page.getByRole('button',{name:'Draw Area',exact:true}).click();
  const surface=page.getByLabel('Area drawing surface');
  await surface.scrollIntoViewIfNeeded();
  const box=await surface.boundingBox();
  await page.mouse.move(box.x+box.width*.35,box.y+box.height*.4);await page.mouse.down();
  await page.mouse.move(box.x+box.width*.65,box.y+box.height*.65,{steps:10});await page.mouse.up();
  await expect(surface).toHaveCount(0);
  await expect(page.locator('.leaflet-tooltip',{hasText:'Selected area'})).toBeVisible();
  expect(dataRequests).toHaveLength(0);
  const panel=page.getByRole('region',{name:'Data query',exact:true});
  await panel.getByRole('checkbox',{name:'Fishing effort',exact:true}).check();
  await load.click();await expect(load).toBeEnabled({timeout:75000});
  expect(dataRequests).toHaveLength(3);
  await expect(page.locator('.evidence-card.obis')).toContainText(/records eligible for map|Locations flagged on land|Locations need review/);
  expect(dataRequests.find(url=>url.includes('/biodiversity/obis'))).not.toContain('start=');
  expect(await page.locator('.leaflet-interactive').count()).toBeGreaterThan(4);
  await page.getByRole('button',{name:'Knowledge graph',exact:true}).click();
  await expect(page.getByRole('region',{name:'Interactive knowledge graph'})).toBeVisible();
  await expect(page.getByRole('button',{name:/^species:/}).first()).toBeVisible();
  // OBIS may have no recent records: explicitly select a historical period for its inventory.
  await page.getByRole('button',{name:'Explore',exact:true}).click();
  await page.getByRole('button',{name:'Arabian Sea',exact:true}).click();
  await page.getByText('Dates & advanced filters',{exact:true}).click();
  await panel.getByLabel('OBIS observation period',{exact:true}).selectOption('selected');
  await panel.getByLabel('From',{exact:true}).fill('1970-01-01');
  await panel.getByLabel('To',{exact:true}).fill('2020-12-31');
  await panel.getByRole('checkbox',{name:'ARGO profiles',exact:true}).uncheck();
  await panel.getByRole('checkbox',{name:'Fishing effort',exact:true}).uncheck();
  await load.click();await expect(load).toBeEnabled({timeout:75000});
  await page.getByRole('button',{name:'Biodiversity',exact:true}).click();
  const card=page.locator('.species-grid article').first();
  await expect(card).toBeVisible({timeout:10000});
  await card.getByText('Observation records and provenance',{exact:true}).click();
  await expect(card.getByRole('table')).toBeVisible();
  await page.getByRole('button',{name:'Knowledge graph',exact:true}).click();
  const graph=page.getByRole('region',{name:'Interactive knowledge graph'});
  await graph.getByRole('button',{name:/^species:/}).first().click();
  await graph.getByRole('button',{name:'Resolve with WoRMS'}).click();
  await expect(graph.getByText('WoRMS classification',{exact:true})).toBeVisible({timeout:35000});
  await graph.getByRole('button',{name:'Zoom in'}).click();await graph.getByRole('button',{name:'Fit to view'}).click();
  await mkdir('../artifacts',{recursive:true});
  await page.screenshot({path:'../artifacts/knowledge-graph.png',fullPage:true});
  await page.getByRole('button',{name:'Explore',exact:true}).click();
  await page.getByRole('button',{name:'Ask Atlas about this area',exact:true}).click();
  await expect(page.getByText('Exploring your selected area',{exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  expect(errors).toEqual([]);
  console.log('LIVE PASS: explicit draw/load, ARGO/OBIS/GFW requests, historical biodiversity record, clickable graph/species, WoRMS, chat context, mobile layout. LLM not invoked by this browser check.');
} finally {await browser.close();}
